/* eslint-disable @typescript-eslint/naming-convention */
export enum BW_LIST {
  BLACK_LIST = 'BLACK_LIST',
  WHITE_LIST = 'WHITE_LIST',
}

export enum SERVICE_TYPES {
  MEETING = 'MEETING',
  FREELANCING_WORK = 'FREELANCING_WORK',
  FULL_TIME_JOB = 'FULL_TIME_JOB',
  PART_TIME_JOB = 'PART_TIME_JOB',
  ROUND_ROBIN = 'ROUND_ROBIN',
}

export enum PAYMENT_STATUS {
  PAID = 'PAID',
  UNPAID = 'UNPAID',
  PENDING = 'PENDING',
}

export enum ORDER {
  ORDER_COMPLETED = 'ORDER_COMPLETED',
  ORDER_NOT_COMPLETED = 'ORDER_NOT_COMPLETED',
  ORDER_CONFIRMED = 'ORDER_CONFIRMED',
  ORDER_NOT_CONFIRMED = 'ORDER_NOT_CONFIRMED',
  ORDER_NOT_CANCELLED = 'ORDER_NOT_CANCELLED',
  ORDER_CANCELLED = 'ORDER_CANCELLED',
  ORDER_CANCELLED_EVENT_NOT_DELETED = 'ORDER_CANCELLED_EVENT_NOT_DELETED',
}

export enum PAYMENT_TYPE {
  ESCROW = 'escrow',
  DIRECT = 'direct',
  MANUAL = 'manual',
}

export enum PAYMENT_ACCOUNTS {
  STRIPE = 'stripe',
}

export enum DIRECT_PAYMENT_OPTIONS {
  STRIPE = 'Stripe',
}

export enum ESCROW_PAYMENT_OPTIONS {
  STRIPE = 'Stripe',
}

export enum AUTHENTICATION_TYPE {
  NONE = 'NONE',
  VERIFIED_ONLY = 'VERIFIED_ONLY',
  PRE_APPROVED = 'PRE_APPROVED',
}
